/**
 * CustomContainerBuilder — Builds Podman images for custom model runtimes.
 *
 * For custom models that need a specific source repository and runtime:
 * 1. Creates a temp working directory inside cacheDir
 * 2. Clones the sourceRepo (if specified in the definition)
 * 3. Generates a Dockerfile from the definition's template or a default template
 * 4. Generates a standard api_wrapper.py entrypoint if the source has no entrypoint
 * 5. Runs `podman build` (10-minute timeout) and returns the image tag
 * 6. Cleans up temp directory
 *
 * Image tag format: aionima-custom-{sanitized-model-id}:latest
 */

import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, writeFileSync, rmSync, existsSync } from "node:fs";
import { join } from "node:path";
import type { CustomRuntimeDefinition } from "./types.js";

// ---------------------------------------------------------------------------
// Default Dockerfile template
// ---------------------------------------------------------------------------

function buildDefaultDockerfile(def: CustomRuntimeDefinition): string {
  const port = String(def.internalPort);
  const extraPips = def.extraPipDeps && def.extraPipDeps.length > 0
    ? `RUN pip install --no-cache-dir ${def.extraPipDeps.join(" ")}\n`
    : "";

  if (def.sourceRepo) {
    return `FROM docker.io/python:3.11-slim
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
RUN git clone ${def.sourceRepo} /src
WORKDIR /src
RUN pip install --no-cache-dir -r requirements.txt || true
RUN pip install --no-cache-dir fastapi uvicorn huggingface-hub safetensors
${extraPips}COPY api_wrapper.py /app/api_wrapper.py
EXPOSE ${port}
ENTRYPOINT ["python", "/app/api_wrapper.py"]
`;
  }

  // No source repo — use a bare Python FastAPI image
  return `FROM docker.io/python:3.11-slim
RUN pip install --no-cache-dir fastapi uvicorn huggingface-hub safetensors
${extraPips}COPY api_wrapper.py /app/api_wrapper.py
EXPOSE ${port}
ENTRYPOINT ["python", "/app/api_wrapper.py"]
`;
}

// ---------------------------------------------------------------------------
// Default api_wrapper.py — minimal FastAPI passthrough for source repo models
// ---------------------------------------------------------------------------

function buildDefaultWrapper(def: CustomRuntimeDefinition): string {
  const port = String(def.internalPort);
  const healthPath = def.healthCheckPath;

  return `"""
Aionima generic API wrapper for custom model: ${def.id}
Auto-generated by CustomContainerBuilder — replace with a model-specific entrypoint.
"""

import os
import sys
import uvicorn
from fastapi import FastAPI

# Add source repo to path so custom model classes can be imported
sys.path.insert(0, "/src")

app = FastAPI(title="${def.label}", version="0.1.0")

_ready = False


@app.on_event("startup")
async def startup():
    global _ready
    # TODO: load model-specific classes here
    _ready = True


@app.get("${healthPath}")
def health():
    return {"status": "ok" if _ready else "loading", "model": "${def.id}"}


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=${port}, log_level="info")
`;
}

// ---------------------------------------------------------------------------
// CustomContainerBuilder
// ---------------------------------------------------------------------------

export class CustomContainerBuilder {
  constructor(private readonly cacheDir: string) {}

  /**
   * Build a custom container image for a model.
   *
   * @param modelId  The HuggingFace model ID (e.g. "NeoQuasar/Kronos-base").
   * @param definition  The custom runtime definition for this model.
   * @returns The image tag that was built (e.g. "aionima-custom-neoquasar--kronos-base:latest").
   */
  async build(modelId: string, definition: CustomRuntimeDefinition): Promise<string> {
    const imageTag = `aionima-custom-${this.sanitizeModelId(modelId)}:latest`;

    // Skip build if the image already exists in the local store
    try {
      execFileSync("podman", ["image", "exists", imageTag], { stdio: "pipe", timeout: 10_000 });
      // Image already present — no rebuild needed
      return imageTag;
    } catch {
      // Image absent — proceed with build
    }

    // Create a temp directory for the build context
    mkdirSync(this.cacheDir, { recursive: true });
    const buildDir = mkdtempSync(join(this.cacheDir, "build-"));

    try {
      // Clone source repo into build context
      if (definition.sourceRepo) {
        const cloneArgs = ["clone", "--depth", "1"];
        if (definition.sourceRef) {
          cloneArgs.push("--branch", definition.sourceRef);
        }
        cloneArgs.push(definition.sourceRepo, join(buildDir, "src"));

        execFileSync("git", cloneArgs, {
          stdio: "pipe",
          timeout: 120_000,
        });
      }

      // Write Dockerfile
      const dockerfile = definition.dockerfileTemplate ?? buildDefaultDockerfile(definition);
      writeFileSync(join(buildDir, "Containerfile"), dockerfile, "utf8");

      // Write api_wrapper.py — only if the source repo does not ship its own entrypoint
      const wrapperPath = join(buildDir, "api_wrapper.py");
      const srcEntrypoint = join(buildDir, "src", "entrypoint.py");
      if (!existsSync(srcEntrypoint)) {
        writeFileSync(wrapperPath, buildDefaultWrapper(definition), "utf8");
      }

      // Run podman build
      execFileSync(
        "podman",
        [
          "build",
          "-t", imageTag,
          "-f", "Containerfile",
          ".",
        ],
        {
          cwd: buildDir,
          stdio: "pipe",
          timeout: 600_000, // 10 minutes
        },
      );

      return imageTag;
    } finally {
      // Always clean up temp dir
      try {
        rmSync(buildDir, { recursive: true, force: true });
      } catch {
        // Non-fatal — temp cleanup failure should not mask the real result
      }
    }
  }

  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------

  /** Produce a safe image name segment from an arbitrary model ID. */
  private sanitizeModelId(modelId: string): string {
    return modelId
      .replace(/\//g, "--")
      .replace(/[^a-zA-Z0-9-]/g, "")
      .toLowerCase();
  }
}
