/**
 * Skill Marketplace Backend — Task #213
 *
 * Skill manifest and marketplace management:
 * - Skill listing with verification status
 * - Submission and review pipeline
 * - Usage stats aggregation
 * - Recognition/endorsement records
 * - All free in Phase 4 (no monetization yet)
 */

import type { RecognitionDomain } from "./recognition.js";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Verification status for marketplace skills. */
export type SkillVerificationStatus = "unreviewed" | "reviewed" | "flagged";

/** A skill listing in the marketplace. */
export interface SkillListing {
  id: string;
  /** Skill name. */
  name: string;
  /** Description of what the skill does. */
  description: string;
  /** Author's entity ID. */
  authorId: string;
  /** Author's GEID. */
  authorGeid: string;
  /** Author's COA fingerprint. */
  authorCoa: string;
  /** Domains this skill operates in. */
  domains: RecognitionDomain[];
  /** Semantic version string. */
  version: string;
  /** Verification status. */
  verificationStatus: SkillVerificationStatus;
  /** Tags for search. */
  tags: string[];
  /** Usage statistics. */
  stats: SkillUsageStats;
  /** Endorsement count. */
  endorsementCount: number;
  /** Originating node. */
  sourceNode: string;
  /** ISO timestamp. */
  createdAt: string;
  /** ISO timestamp of last update. */
  updatedAt: string;
  /** Whether the skill is published (visible in marketplace). */
  published: boolean;
}

/** Usage statistics for a skill. */
export interface SkillUsageStats {
  /** Total installations. */
  installs: number;
  /** Current active installations. */
  activeInstalls: number;
  /** Uninstalls (quick-remove). */
  uninstalls: number;
  /** Retention rate (1 - quickRemoveRate). */
  retentionRate: number;
  /** Average $imp generated by users of this skill. */
  avgImpCorrelation: number;
}

/** A skill endorsement. */
export interface SkillEndorsement {
  id: string;
  skillId: string;
  endorserId: string;
  endorserGeid: string;
  comment: string;
  createdAt: string;
}

/** Parameters for submitting a skill. */
export interface SubmitSkillParams {
  id: string;
  name: string;
  description: string;
  authorId: string;
  authorGeid: string;
  authorCoa: string;
  domains: RecognitionDomain[];
  version: string;
  tags?: string[];
  sourceNode: string;
}

// ---------------------------------------------------------------------------
// Marketplace Manager
// ---------------------------------------------------------------------------

/**
 * Manages the skill marketplace.
 */
export class MarketplaceManager {
  private readonly skills = new Map<string, SkillListing>();
  private readonly endorsements = new Map<string, SkillEndorsement[]>();
  /** Track installs: userId → Set of skillIds. */
  private readonly userInstalls = new Map<string, Set<string>>();

  /**
   * Submit a new skill to the marketplace.
   */
  submit(params: SubmitSkillParams): SkillListing {
    const listing: SkillListing = {
      id: params.id,
      name: params.name,
      description: params.description,
      authorId: params.authorId,
      authorGeid: params.authorGeid,
      authorCoa: params.authorCoa,
      domains: [...params.domains],
      version: params.version,
      verificationStatus: "unreviewed",
      tags: params.tags ? [...params.tags] : [],
      stats: {
        installs: 0,
        activeInstalls: 0,
        uninstalls: 0,
        retentionRate: 1.0,
        avgImpCorrelation: 0,
      },
      endorsementCount: 0,
      sourceNode: params.sourceNode,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      published: false,
    };

    this.skills.set(params.id, listing);
    return listing;
  }

  /**
   * Publish a skill (make visible in marketplace).
   */
  publish(skillId: string): SkillListing {
    const skill = this.getOrThrow(skillId);
    skill.published = true;
    skill.updatedAt = new Date().toISOString();
    return skill;
  }

  /**
   * Update verification status (review pipeline).
   */
  setVerificationStatus(skillId: string, status: SkillVerificationStatus): SkillListing {
    const skill = this.getOrThrow(skillId);
    skill.verificationStatus = status;
    skill.updatedAt = new Date().toISOString();
    return skill;
  }

  /**
   * Record a skill installation by a user.
   */
  install(skillId: string, userId: string): void {
    const skill = this.getOrThrow(skillId);

    if (!this.userInstalls.has(userId)) {
      this.userInstalls.set(userId, new Set());
    }
    const installs = this.userInstalls.get(userId)!;

    if (installs.has(skillId)) return; // Already installed

    installs.add(skillId);
    skill.stats.installs++;
    skill.stats.activeInstalls++;
    this.recalcRetention(skill);
  }

  /**
   * Record a skill uninstall.
   */
  uninstall(skillId: string, userId: string): void {
    const skill = this.getOrThrow(skillId);
    const installs = this.userInstalls.get(userId);

    if (!installs?.has(skillId)) return; // Not installed

    installs.delete(skillId);
    skill.stats.activeInstalls = Math.max(0, skill.stats.activeInstalls - 1);
    skill.stats.uninstalls++;
    this.recalcRetention(skill);
  }

  /**
   * Add an endorsement for a skill.
   */
  endorse(params: {
    id: string;
    skillId: string;
    endorserId: string;
    endorserGeid: string;
    comment: string;
  }): SkillEndorsement {
    const skill = this.getOrThrow(params.skillId);

    const endorsement: SkillEndorsement = {
      id: params.id,
      skillId: params.skillId,
      endorserId: params.endorserId,
      endorserGeid: params.endorserGeid,
      comment: params.comment,
      createdAt: new Date().toISOString(),
    };

    if (!this.endorsements.has(params.skillId)) {
      this.endorsements.set(params.skillId, []);
    }
    this.endorsements.get(params.skillId)!.push(endorsement);
    skill.endorsementCount++;

    return endorsement;
  }

  /**
   * Get endorsements for a skill.
   */
  getEndorsements(skillId: string): SkillEndorsement[] {
    return this.endorsements.get(skillId) ?? [];
  }

  /**
   * Search skills by domain, tag, or text query.
   */
  search(query: {
    domain?: RecognitionDomain;
    tag?: string;
    text?: string;
    verificationStatus?: SkillVerificationStatus;
  }): SkillListing[] {
    const results: SkillListing[] = [];

    for (const skill of this.skills.values()) {
      if (!skill.published) continue;

      if (query.domain && !skill.domains.includes(query.domain)) continue;
      if (query.tag && !skill.tags.includes(query.tag)) continue;
      if (query.verificationStatus && skill.verificationStatus !== query.verificationStatus) continue;
      if (query.text) {
        const lower = query.text.toLowerCase();
        if (
          !skill.name.toLowerCase().includes(lower) &&
          !skill.description.toLowerCase().includes(lower)
        ) {
          continue;
        }
      }

      results.push(skill);
    }

    return results;
  }

  /**
   * Get all published skills.
   */
  listPublished(): SkillListing[] {
    return Array.from(this.skills.values()).filter(s => s.published);
  }

  /** Get a skill by ID. */
  get(skillId: string): SkillListing | null {
    return this.skills.get(skillId) ?? null;
  }

  /**
   * Check if a user has a skill installed.
   */
  isInstalled(skillId: string, userId: string): boolean {
    return this.userInstalls.get(userId)?.has(skillId) ?? false;
  }

  // -------------------------------------------------------------------------
  // Private
  // -------------------------------------------------------------------------

  private getOrThrow(skillId: string): SkillListing {
    const skill = this.skills.get(skillId);
    if (!skill) throw new Error(`Skill not found: ${skillId}`);
    return skill;
  }

  private recalcRetention(skill: SkillListing): void {
    if (skill.stats.installs === 0) {
      skill.stats.retentionRate = 1.0;
    } else {
      skill.stats.retentionRate = skill.stats.activeInstalls / skill.stats.installs;
    }
  }
}
