#!/usr/bin/env bash
# client-dns-setup.sh — Configure this machine to resolve *.ai.on via the Aionima server.
# Works on macOS (networksetup) and Linux (systemd-resolved).
#
# Usage:
#   curl -sL http://ai.on:3100/api/hosting/client-setup/linux | sudo bash
#   curl -sL http://ai.on:3100/api/hosting/client-setup/macos | sudo bash
#
# Override the Aionima server IP:
#   AIONIMA_IP=10.0.0.5 sudo bash client-dns-setup.sh

set -euo pipefail

AIONIMA_IP="${AIONIMA_IP:-${NEXUS_IP:-__AIONIMA_IP__}}"
BASE_DOMAIN="${BASE_DOMAIN:-__BASE_DOMAIN__}"

echo "==> Configuring DNS to resolve *.${BASE_DOMAIN} via ${AIONIMA_IP}"

# --------------------------------------------------------------------------
# Detect OS
# --------------------------------------------------------------------------

case "$(uname -s)" in
  Darwin)
    OS="macos"
    ;;
  Linux)
    OS="linux"
    ;;
  *)
    echo "ERROR: Unsupported OS: $(uname -s)" >&2
    exit 1
    ;;
esac

# --------------------------------------------------------------------------
# macOS — prepend DNS server to the active network service
# --------------------------------------------------------------------------

if [ "$OS" = "macos" ]; then
  # Collect active network services (those with an IPv4 address)
  SERVICES=()
  SERVICE_IPS=()
  SERVICE_DNS=()
  while IFS= read -r service; do
    [ -z "$service" ] && continue
    info=$(networksetup -getinfo "$service" 2>/dev/null || true)
    ip=$(echo "$info" | grep "^IP address:" | head -1 | awk '{print $3}')
    [ -z "$ip" ] && continue
    dns=$(networksetup -getdnsservers "$service" 2>/dev/null || true)
    if echo "$dns" | grep -q "There aren't any DNS Servers"; then
      dns="(automatic)"
    else
      dns=$(echo "$dns" | tr '\n' ', ' | sed 's/,$//')
    fi
    SERVICES+=("$service")
    SERVICE_IPS+=("$ip")
    SERVICE_DNS+=("$dns")
  done < <(networksetup -listallnetworkservices | tail -n +2)

  if [ ${#SERVICES[@]} -eq 0 ]; then
    echo "ERROR: No active network service with an IPv4 address found." >&2
    exit 1
  fi

  if [ ${#SERVICES[@]} -eq 1 ]; then
    ACTIVE_SERVICE="${SERVICES[0]}"
    echo "    Active service: ${ACTIVE_SERVICE} - ${SERVICE_IPS[0]}"
  else
    echo ""
    echo "    Multiple active services found:"
    for i in "${!SERVICES[@]}"; do
      echo "      [$((i + 1))] ${SERVICES[$i]}"
      echo "           IP: ${SERVICE_IPS[$i]}  DNS: ${SERVICE_DNS[$i]}"
    done
    echo ""
    while true; do
      printf "    Select service [1-%d]: " "${#SERVICES[@]}"
      read -r choice
      if [ "$choice" -ge 1 ] 2>/dev/null && [ "$choice" -le "${#SERVICES[@]}" ] 2>/dev/null; then
        break
      fi
    done
    ACTIVE_SERVICE="${SERVICES[$((choice - 1))]}"
    echo "    Selected: ${ACTIVE_SERVICE} (${SERVICE_IPS[$((choice - 1))]})"
  fi

  # Get current DNS servers
  CURRENT_DNS=$(networksetup -getdnsservers "$ACTIVE_SERVICE" 2>/dev/null || true)
  if echo "$CURRENT_DNS" | grep -q "There aren't any DNS Servers"; then
    CURRENT_DNS=""
  fi

  # Check if already configured
  if echo "$CURRENT_DNS" | grep -q "^${AIONIMA_IP}$"; then
    echo "    DNS already includes ${AIONIMA_IP} — nothing to do."
  else
    # Prepend Aionima IP
    # shellcheck disable=SC2086
    networksetup -setdnsservers "$ACTIVE_SERVICE" "$AIONIMA_IP" $CURRENT_DNS
    echo "    DNS servers set: ${AIONIMA_IP} ${CURRENT_DNS}"
  fi

  # Flush macOS DNS cache
  dscacheutil -flushcache 2>/dev/null || true
  killall -HUP mDNSResponder 2>/dev/null || true
  echo "    DNS cache flushed."
fi

# --------------------------------------------------------------------------
# Linux (systemd-resolved) — add drop-in config for the ai.on domain
# --------------------------------------------------------------------------

if [ "$OS" = "linux" ]; then
  CONF_DIR="/etc/systemd/resolved.conf.d"
  CONF_FILE="${CONF_DIR}/ai-on.conf"

  if [ ! -d "$CONF_DIR" ]; then
    mkdir -p "$CONF_DIR"
    echo "    Created ${CONF_DIR}"
  fi

  cat > "$CONF_FILE" <<EOF
# Auto-generated by aionima client-dns-setup
[Resolve]
DNS=${AIONIMA_IP}
Domains=~${BASE_DOMAIN}
EOF

  echo "    Wrote ${CONF_FILE}"

  # Restart systemd-resolved
  if systemctl is-active --quiet systemd-resolved; then
    systemctl restart systemd-resolved
    echo "    systemd-resolved restarted."
  else
    echo "    WARNING: systemd-resolved is not active. You may need to restart your DNS resolver manually."
  fi
fi

# --------------------------------------------------------------------------
# Verify
# --------------------------------------------------------------------------

echo ""
echo "==> Verifying: dig test.${BASE_DOMAIN} @${AIONIMA_IP}"

if command -v dig &>/dev/null; then
  RESULT=$(dig +short "test.${BASE_DOMAIN}" "@${AIONIMA_IP}" 2>/dev/null || true)
  if [ -n "$RESULT" ]; then
    echo "    OK — test.${BASE_DOMAIN} resolves to ${RESULT}"
  else
    echo "    WARNING: No response from ${AIONIMA_IP} for test.${BASE_DOMAIN}."
    echo "    The dnsmasq server may not be running or configured yet."
  fi
else
  echo "    dig not found — install dnsutils/bind-utils to verify manually."
fi

# --------------------------------------------------------------------------
# Install Caddy internal CA certificate (for HTTPS trust)
# --------------------------------------------------------------------------

echo ""
echo "==> Installing Aionima CA certificate for HTTPS trust"

CA_URL="http://${AIONIMA_IP}:3100/api/hosting/ca-cert"
CA_CERT=$(curl -sL "$CA_URL" 2>/dev/null || true)

if [ -z "$CA_CERT" ] || echo "$CA_CERT" | grep -q '"error"'; then
  echo "    WARNING: Could not download CA cert from ${CA_URL}."
  echo "    HTTPS sites will show browser warnings until the CA is trusted."
  echo "    You can retry later: curl -sL ${CA_URL} -o aionima-ca.crt"
else
  if [ "$OS" = "macos" ]; then
    CA_FILE="/tmp/aionima-ca.crt"
    echo "$CA_CERT" > "$CA_FILE"
    security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain "$CA_FILE"
    rm -f "$CA_FILE"
    echo "    CA certificate added to System Keychain."
  elif [ "$OS" = "linux" ]; then
    CA_DIR="/usr/local/share/ca-certificates"
    mkdir -p "$CA_DIR"
    echo "$CA_CERT" > "${CA_DIR}/aionima-ca.crt"
    update-ca-certificates 2>/dev/null || true
    echo "    CA certificate installed to system trust store"

    # Chrome/Chromium on Linux uses the NSS shared DB
    for nssdb in "$HOME/.pki/nssdb" /etc/pki/nssdb; do
      if [ -d "$nssdb" ]; then
        certutil -d "sql:${nssdb}" -A -t "C,," -n "Aionima Local CA" -i "${CA_DIR}/aionima-ca.crt" 2>/dev/null \
          && echo "    CA added to NSS DB (${nssdb}) — Chrome/Chromium will trust it" \
          || echo "    NOTE: Install libnss3-tools to add CA to Chrome: sudo apt install libnss3-tools"
      fi
    done

    # Firefox uses per-profile cert9.db
    for profile in "$HOME"/.mozilla/firefox/*.default* "$HOME"/snap/firefox/common/.mozilla/firefox/*.default*; do
      [ -d "$profile" ] || continue
      certutil -d "sql:${profile}" -A -t "C,," -n "Aionima Local CA" -i "${CA_DIR}/aionima-ca.crt" 2>/dev/null \
        && echo "    CA added to Firefox profile: $(basename "$profile")" \
        || true
    done
  fi
fi

echo ""
echo "Done. This machine should now resolve *.${BASE_DOMAIN} via ${AIONIMA_IP}."
echo "      HTTPS sites at https://*.${BASE_DOMAIN} should be trusted."
